# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Paolo Matteoni
title: Aerospace Engineer
# email: email@gmail.com
website: www.paolomatteoni.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: polmdm
# github_username:  polmdm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: paolo.matteoni
linkedin_username: paolo-matteoni
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Paolo and I'm young space engineer, mostly. I stand out in creativity and innovation, that's why I carry out tons of projects and ideas in my free time. Some of them are simply hoobies, others real business.

  I am currently working on my MSc thesis while designing and producing dedicated nano-satellite hardware and software at Spacemind.

  I am most skilled in: <mark>Matlab</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Ideas # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Spacemind
        link: npcspacemind.com
        # link_text: boringcompany.com
        sub_title: System Engineer
        caption: October 2020 - Present
        quote: >
          Spacemind's core business is focused on research and development of products dedicated to space sector.

        description: | # this will include new lines to allow paragraphs
            Development, production and integration of nano-satellite's Electrical Power System and Solar Panels.
      - layout: left
        title: Hotel Benini
        link: hotelbenini.it
        # link_text: boringcompany.com
        sub_title: Administrative Secretary
        caption: June 2014 - September 2019
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Long standing back office experience in management, administration and technical skills of family's owned hotel.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Politecnico di Milano
        caption: 2019 - Present
        sub_title: MSc Space Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **City:** Milano, Italy üáÆüáπ

          **Final Grade:** TBD

          **Thesis:** TBD

          **Internship:** TBD

          Politecnico di Milano is a scientific-technological university which trains engineers, architects and industrial designers.
          The University has always focused on the quality and innovation of its teaching and research, developing a fruitful relationship with business and productive world by means of experimental research and technological transfer.

      - layout: left
        title: Universit√† di Bologna
        caption: 2016 - 2019
        sub_title: BSc Aerospace Engineering
        # quote: >
        #   "Forl√¨, Italy | Final grade: 110 with honours"
        description: | # this will include new lines to allow paragraphs
          **City:** Forl√¨, Italy üáÆüáπ

          **Final Grade:** 110 cum laude

          **Thesis:** Design and Sizing of CubeSat's Power Subsystem.

          **Internship:** Spacemind: design, development and testing of Cubesat's Electrical Power System.

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

      - layout: left
        title: Liceo Scientifico "Albert Einstein"
        caption: 2011 - 2016
        sub_title: Scientific High School Degree
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **City:** Rimini, Italy üáÆüáπ

          **Final Grade:** 100/100

          **Thesis:** Legosat

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: TEASPOON - SMAD
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The course teaches how to put in practice the fundamentals to accomplish a complete feasibility study and pre-phase A phase for a Space mission, according to the Agencies standards.

        description: | # this will include new lines to allow paragraphs
          Power budget and Electrical Power System design of TEASPOON - a space mission to the Outer Solar System, aimed at studying Sedna and discover new Kuiper Belt Objects.
          Supervisor: Mich√®le Lavagna.

      - layout: top-middle
        title: Concurrent Engineering Challenge
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The CDF‚Äôs infrastructure, methodology and processes allow teams of experts from different engineering disciplines to work in close coordination in the same place at the same time to complete the most complex designs imaginable.
        description: | # this will include new lines to allow paragraphs
          Phase 0 of a space mission aimed at studying Enceladus, a moon of Saturn, at ESA Concurrent Facility, ESEC - Galaxia, Belgium.

      - layout: top-middle
        title: European Cansat Competition - Legosat
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A CanSat is a simulation of a real satellite, integrated within the volume and shape of a soft drink can. The team‚Äôs challenge is to fit all the major subsystems of a satellite inside this minimal volume, launched by a small rocket up to an altitude of 1 km. As the CanSat descends, its mission begins.
        description: | # this will include new lines to allow paragraphs
          Legosat introduces a modular design for CanSats exploiting Lego and control system, fans' based, for a controlled reentry. Legosat challenged both into Italian and European Cansat final competition.

  # - title: Memberships # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Rotaract
  #       caption: 2020 - Present
  #       sub-title: President
  #       link: rotaractclubrimini.wordpress.com
  #       link_text: rotaractclubrimini.it
  #       additional_links:
  #        - title:  Instagram
  #          icon: fab fa-instagram
  #          url: instagram.com/rotaract_club_rimini
  #        - title:  Facebook
  #          icon: fab fa-facebook
  #          url: facebook.com/rotaract_club_rimini
  #       quote: >
  #         Fellowship Through Service
  #       description: | # this will include new lines to allow paragraphs
  #         President of Rotaract Club Rimini
  #     - layout: left
  #       title: Euroavia
  #       caption: 2018 - 2019
  #       sub_title: IT Manager
  #       link: euroaviaforlibologna.eu
  #       # link_text: Association Website
  #       additional_links:
  #        - title:  Instagram
  #          icon: fab fa-instagram
  #          url: instagramcom/euroaviaforlibologna
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       # quote: >
  #       #   Fellowship through service. Paoul Harris
  #       # description: | # this will include new lines to allow paragraphs
  #       #   President of Rotaract Club Rimini

  - title: My skills
    layout: text
    content: | # this will include new lines to allow paragraphs
    <mark>UNIX</mark> / <mark>Office 365</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in engineering and software some of my other interests and hobbies are:
      - Motorbike
      - 3D Printing
      - SUP
      - Technology
      - Photography and videography

      Moreover I am member of Euroavia Forl√¨ Bologna and president of Rotaract Club Rimini.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
